# Generated by Django 2.1.2 on 2018-11-11 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Verb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dictionary_string', models.CharField(max_length=30)),
                ('translation', models.TextField()),
                ('verb_type', models.CharField(choices=[('godan', 'Goddan'), ('ichidan', 'Ichidan'), ('suru', '~Suru'), ('kuru', '~kuru')], max_length=10)),
                ('genki_chapter', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
