# Generated by Django 2.1.2 on 2018-11-11 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verb',
            name='translation',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='verb',
            name='verb_type',
            field=models.CharField(choices=[('godan', 'Godan'), ('ichidan', 'Ichidan'), ('suru', '~Suru'), ('kuru', '~Kuru')], max_length=10),
        ),
    ]
