# Generated by Django 2.1.2 on 2018-11-22 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20181120_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='verb',
            name='has_tai_form',
            field=models.BooleanField(default=True, verbose_name=True),
            preserve_default=False,
        ),
    ]
